main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.story7, name='story7'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.story8, name='story8'),
    path('data', views.hasil_search, name='data'),
]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('sign-up/', views.sign_up, name='signup'),
    path('log-in/', views.log_in, name='login'),
    path('', views.log_out, name='logout'),
]

story_aran/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='home')),
    path('story-7/', include('story7.urls', namespace='story7')),
    path('story-8/', include('story8.urls', namespace='story8')),
    path('story-9/', include('story9.urls', namespace='story9')),
]

main/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

story9/forms.py
from django import forms
from .models import Profile
from django.contrib.auth import get_user_model

User = get_user_model()

class FormLogin(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'style':'width:100%; border-radius:5px; border:none'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'style':'width:100%; border-radius:5px; border:none'}))

class FormSignup(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'style':'width:100%; border-radius:5px; border:none'}), label="Username:")
    email = forms.EmailField(widget=forms.EmailInput(attrs={'style':'width:100%; border-radius:5px; border:none'}), label="E-mail:")
    password_awal = forms.CharField(label="Password:", widget=forms.PasswordInput(attrs={'style':'width:100%; border-radius:5px; border:none'}))
    password_lagi = forms.CharField(label="Confirm password:", widget=forms.PasswordInput(attrs={'style':'width:100%; border-radius:5px; border:none'}))

    def clean(self):
        cleaned_data = self.cleaned_data
        password_satu = self.cleaned_data.get('password_awal')
        password_dua = self.cleaned_data.get('password_lagi')
        if password_satu != password_dua:
            raise forms.ValidationError("Passwords don't match")
        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        user_by_name = User.objects.filter(username=username)
        if user_by_name.exists():
            raise forms.ValidationError("The username you've chosen is unavailable.")
        return username

    def clean_email(self):
        email_address = self.cleaned_data.get('email')
        user_by_email = User.objects.filter(email=email_address)
        if user_by_email.exists():
            raise forms.ValidationError("The email address you've chosen is already registered.")
        return email_address

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

story7/views.py
from django.shortcuts import render

# Create your views here.
def story7(request):
    return render(request, 'story7/storyaccordion.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.

def story8(request):
    response = {}
    return render(request, 'story8/booklist.html', response)

def hasil_search(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    res = requests.get(url)
    data = json.loads(res.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from .models import Profile
from .forms import FormLogin, FormSignup

User = get_user_model()

def sign_up(request):
    form_signup = FormSignup(request.POST or None)
    context = {
        'form_signup': form_signup,
    }
    if form_signup.is_valid():
        username = form_signup.cleaned_data.get('username')
        email = form_signup.cleaned_data.get('email')
        password = form_signup.cleaned_data.get('password_awal')
        User.objects.create_user(username, email, password)

        return HttpResponseRedirect('/story-9/log-in')
    return render(request, 'story9/signup.html', context=context)

def log_in(request):
    form_login = FormLogin(request.POST or None)
    context = {
        'form_login': form_login
    }
    print(request.user.is_authenticated)
    if form_login.is_valid():
        print(form_login.cleaned_data)
        username = form_login.cleaned_data.get('username')
        password = form_login.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            print("error.......")

    return render(request, 'story9/login.html', context=context)

def log_out(request):
    logout(request)
    return render(request, 'main/home.html')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link href="{% static 'stylemain.css' %}" rel="stylesheet" type="text/css">
{% endblock meta %}

{% block content %}
  {% if user.is_authenticated %}
    <div div class="d-flex justify-content-center" style="font-family: 'DM Serif Display', serif; margin-top: 15vh; color: #BBAAA0 ;"> 
        <h2>Hello, <span style="color:#734631">{{ user.username }}</span>! Have a great day!</h2>
    </div>

    <div class="d-flex justify-content-center" style="font-family: 'DM Serif Display', serif; margin-top: 5vh; color: #BBAAA0;"> 
        <p>Congratulations! You've just got yourself a treasure!</p>
    </div>
    <div class="d-flex justify-content-center mb-5">
      <iframe src="https://open.spotify.com/embed/track/1bL26HXVXnIwof5WL92HaG" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
    </div>
    
    {% else %}
    <div class="home">
      <div class="square">
        <p class="text h1">Hello, there!</p>
      </div>
    </div>
    {% endif %}
{% endblock content %}

story7/templates/story7/storyaccordion.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link href="{% static 'style7.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'jquery-3.5.1.js'%}"></script>
    <script src="{% static 'story7.js' %}"></script>
{% endblock meta %}

{% block content %}

<div class="d-flex justify-content-center">
    <h3 class="text">Hello, this is Aran</h3>
</div>
<div class="container accordion mb-5">
    <div id="acc-activities">
        <h3>Activities
            <span style="float: right;">
                <button style="font-size: 15px;" class="button-up"><i class="fas fa-angle-up"></i></button>
                <button style="font-size: 15px;" class="button-down"><i class="fas fa-angle-down"></i></button>
            </span>
        </h3>
        <div>
            <p class="accor-text">Kegiatan saya sekarang adalah:</p>
            <ul class="accor-text">
                <li>Kuliah secara online dari rumah karena pandemi</li>
                <li>Ikut kepanitiaan dan organisasi</li>
                <li>Ngerjain tugas</li>
                <li>Makan dan tidur</li>
                <li>Nonton Jae main game</li>
            </ul>
        </div>
    </div>
    <div id="acc-experience">
        <h3>Experience
            <span style="float: right;">
                <button style="font-size: 15px;" class="button-up"><i class="fas fa-angle-up"></i></button>
                <button style="font-size: 15px;" class="button-down"><i class="fas fa-angle-down"></i></button>
            </span>
        </h3>
        <div>
            <p class="accor-text">Pengalaman organisasi dan kepanitiaan saya selama di Fasilkom adalah:</p>
            <ul class="accor-text">
                <li>Staf Biro PSDM BEM Fasilkom UI 2020</li>
                <li>Staf Divisi Fundraising COMPFEST12</li>
                <li>Staf Divisi Humas dan Publikasi Wisuda Ganjil Fasilkom UI 2020</li>
                <li>Staf Divisi Humas dan Publikasi Pemira IKM Fasilkom UI 2019</li>
            </ul>
        </div>
    </div>
    <div id="acc-achievement">
        <h3>Achievement
            <span style="float: right;">
                <button style="font-size: 15px;" class="button-up"><i class="fas fa-angle-up"></i></button>
                <button style="font-size: 15px;" class="button-down"><i class="fas fa-angle-down"></i></button>
            </span>
        </h3>
        <div class="accor-text">
            <p>Prestasi saya:</p>
            <ul>
                <li>Completer Kumon EFL</li>
            </ul>
        </div>
    </div>
    <div id="acc-band">
        <h3>My Favorite Band
            <span style="float: right;">
                <button style="font-size: 15px;" class="button-up"><i class="fas fa-angle-up"></i></button>
                <button style="font-size: 15px;" class="button-down"><i class="fas fa-angle-down"></i></button>
            </span>
        </h3>
        <div class="accor-text">
            <p>Sekarang saya lagi nge-fans banget sama band namanya DAY6</p>
            <p>Member DAY6:</p>
            <ul>
                <li>SUNGJIN</li>
                <li>JAE</li>
                <li>YOUNGK</li>
                <li>WONPIL</li>
                <li>DOWOON</li>
            </ul>
            <p>Lagu-lagu DAY6 yang enak menurut saya:</p>
            <ul>
                <li>Marathon</li>
                <li>Warning</li>
                <li>days gone by</li>
                <li>semuanya</li>
            </ul>
            <p>Ayo semua dengerin lagu DAY6</p>
        </div>
    </div>
</div>

{% endblock content %}

story8/templates/story8/booklist.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
    <script src="{% static 'jquery-3.5.1.js' %}"></script>
    <script src="{% static 'script8.js' %}"></script>
    <link href="{% static 'story8.css' %}" rel="stylesheet" type="text/css">
{% endblock meta %}


{% block content %}
    <div class="d-flex justify-content-center">
        <h3 class="text">Search for books here!</h3>
    </div>

    <div class="container justify-content-center text-center p-5" style="max-width: 700px;">
        <input class="form-control" id="keyword" placeholder="Search...">
    </div>

    <table class="table table-striped justify-content-center text-center">
        <thead>
            <tr>
                <th class="table-text" scope="col">Cover</th>
                <th class="table-text" scope="col">Title</th>
                <th class="table-text" scope="col">Author</th>
            </tr>
        </thead>
        <tbody class="txt-pop"></tbody>
    </table>

{% endblock content %}

story9/templates/story9/login.html
{% extends 'base.html' %} 
{% load static %}
{% block meta %}
    <link href="{% static 'style9.css' %}" rel="stylesheet" type="text/css">
{% endblock meta %}

{% block content %}
<div style="margin-top: 20vh;" class="d-flex justify-content-center">
    <h3 class="text-title">Fill In This Form to Log In</h3>
</div>
<div class="mb-5">
    <div class="d-flex justify-content-center">
        <div class="fr-form">
            <form method="POST" style="width: 100%; font-family: 'Poppins', sans-serif; padding-left: 5%; padding-right: 5%;" class="mt-3">
                {% csrf_token %}
                <div class="form-group">
                    <div class="p-form d-flex justify-content-start">
                        {{form_login.username.label_tag}}
                    </div>
                    {{form_login.username}}
                </div>
                <div class="form-group">
                    <div class="p-jawab d-flex justify-content-start">
                        {{form_login.password.label_tag}}
                    </div>
                    {{form_login.password}}
                </div>
                <div class="d-flex justify-content-end mb-3">
                    <button type="submit" class="btn btn-secondary" style="background-color:#734631;">Log In</button>
                </div>
            </form>
            <div class="mt-3 d-flex justify-content-start">
                <p style="font-family: 'Poppins', sans-serif; padding-left: 5%; padding-right: 5%;">Don't have an account? <a href="{% url 'story9:signup'%}">Sign Up</a></p>
            </div>
        </div>
    </div>
{% endblock content %}

story9/templates/story9/signup.html
{% extends 'base.html' %} 
{% load static %}
{% block meta %}
    <link href="{% static 'style9.css' %}" rel="stylesheet" type="text/css">
{% endblock meta %}

{% block content %}
    <div style="margin-top: 20vh;" class="d-flex justify-content-center">
        <h3 class="text-title">Fill In This Form to Sign Up</h3>
    </div>
    <div class="mb-5">
        <div class="d-flex justify-content-center">
            <div class="fr-form">
                <form method="POST" style="width: 100%; font-family: 'Poppins', sans-serif; padding-left: 5%; padding-right: 5%;" class="mt-3">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="p-form d-flex justify-content-start">
                            {{form_signup.username.label_tag}}
                        </div>
                        {{form_signup.username}}
                    </div>
                    <div class="form-group">
                        <div class="p-jawab d-flex justify-content-start">
                            {{form_signup.email.label_tag}}
                        </div>
                        {{form_signup.email}}
                    </div>
                    <div class="form-group">
                        <div class="p-jawab d-flex justify-content-start">
                            {{form_signup.password_awal.label_tag}}
                        </div>
                        {{form_signup.password_awal}}
                    </div>
                    <div class="form-group">
                        <div class="p-jawab d-flex justify-content-start">
                            {{form_signup.password_lagi.label_tag}}
                        </div>
                        {{form_signup.password_lagi}}
                    </div>
                    <div class="d-flex justify-content-end mb-3">
                        <button type="submit" class="btn btn-secondary" style="background-color:#734631;">Sign Up</button>
                    </div>
                </form>
                <div class="mt-3 d-flex justify-content-start">
                    <p style="font-family: 'Poppins', sans-serif; padding-left: 5%; padding-right: 5%;">Already have an account? <a href="{% url 'story9:login'%}">Log In</a></p>
                </div>
        
            </div>
        </div>
    </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>✰ | Aransandya</title>
        <link rel="icon" href="{% static 'logo.png' %}" type="image/icon type">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {% block meta %} {% endblock meta %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <a class="navbar-brand" href="{% url 'home:home' %}#"><img src="{% static 'logo.png' %}" alt="logo" style="width: 40px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="{% url 'story7:story7' %}" style="font-family: 'Poppins', sans-serif">story 7</a>
                <a class="nav-item nav-link" href="{% url 'story8:story8' %}" style="font-family: 'Poppins', sans-serif">story 8</a>
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'story9:logout' %}" style="font-family: 'Poppins', sans-serif">Log Out</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'story9:login' %}" style="font-family: 'Poppins', sans-serif">Log In</a>
                <a class="nav-item nav-link" href="{% url 'story9:signup' %}" style="font-family: 'Poppins', sans-serif">Sign Up</a>
                {% endif %}
            </div>
            </div>
        </nav>
        {% block content %} {% endblock content %}

        <!-- block for js and jquery accordion -->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    </body>
</html>